// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "yuantaquote.h"

/////////////////////////////////////////////////////////////////////////////
// CYuantaQuote

IMPLEMENT_DYNCREATE(CYuantaQuote, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CYuantaQuote properties

/////////////////////////////////////////////////////////////////////////////
// CYuantaQuote operations

void CYuantaQuote::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CYuantaQuote::SetMktLogon(LPCTSTR user, LPCTSTR pass, LPCTSTR ip, LPCTSTR port)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x0, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 user, pass, ip, port);
}

void CYuantaQuote::SetMktConnection(LPCTSTR user, LPCTSTR ip, LPCTSTR port)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 user, ip, port);
}

long CYuantaQuote::AddMktReg(LPCTSTR symbol, LPCTSTR updmode)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		symbol, updmode);
	return result;
}

long CYuantaQuote::DelMktReg(LPCTSTR symbol)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		symbol);
	return result;
}

void CYuantaQuote::SetLog(long __MIDL_0010)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 __MIDL_0010);
}
