#if !defined(AFX_YUANTAQUOTE_H__23E07F49_1733_4A18_83B7_AE636D9BAABC__INCLUDED_)
#define AFX_YUANTAQUOTE_H__23E07F49_1733_4A18_83B7_AE636D9BAABC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CYuantaQuote wrapper class

class CYuantaQuote : public CWnd
{
protected:
	DECLARE_DYNCREATE(CYuantaQuote)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xe93362d9, 0xdf7e, 0x49d2, { 0x9b, 0x82, 0x8d, 0x83, 0x8b, 0xc0, 0xa0, 0x31 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void AboutBox();
	void SetMktLogon(LPCTSTR user, LPCTSTR pass, LPCTSTR ip, LPCTSTR port);
	void SetMktConnection(LPCTSTR user, LPCTSTR ip, LPCTSTR port);
	long AddMktReg(LPCTSTR symbol, LPCTSTR updmode);
	long DelMktReg(LPCTSTR symbol);
	void SetLog(long __MIDL_0010);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_YUANTAQUOTE_H__23E07F49_1733_4A18_83B7_AE636D9BAABC__INCLUDED_)
